# Generated by Django 3.2.14 on 2023-07-16 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField(max_length=255, verbose_name='紹介文')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='生年月日')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='accounts/user_images/', verbose_name='サムネイル')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
